name: pythia8-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.6
  - jupyter
  - ipykernel
  - metakernel
  - root
  - pythia8
  - gcc
  - gxx
  - cmake
  - make
  - numpy
  - scipy